# Generated by Django 2.2 on 2019-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191028_2046'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Endereços'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'verbose_name_plural': 'Cupons'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name_plural': 'Pagamentos'},
        ),
        migrations.AlterModelOptions(
            name='refund',
            options={'verbose_name_plural': 'Reembolsos'},
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
